// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/orishu/deeb/internal/transport (interfaces: Client)

// Package transport is a generated GoMock package.
package transport

import (
	context "context"
	reflect "reflect"

	raftpb "go.etcd.io/etcd/raft/v3/raftpb"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddNewPeer mocks base method.
func (m *MockClient) AddNewPeer(arg0 context.Context, arg1 uint64, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewPeer", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewPeer indicates an expected call of AddNewPeer.
func (mr *MockClientMockRecorder) AddNewPeer(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewPeer", reflect.TypeOf((*MockClient)(nil).AddNewPeer), arg0, arg1, arg2, arg3)
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// GetHighestID mocks base method.
func (m *MockClient) GetHighestID(arg0 context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestID", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighestID indicates an expected call of GetHighestID.
func (mr *MockClientMockRecorder) GetHighestID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestID", reflect.TypeOf((*MockClient)(nil).GetHighestID), arg0)
}

// GetRemoteID mocks base method.
func (m *MockClient) GetRemoteID(arg0 context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteID", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteID indicates an expected call of GetRemoteID.
func (mr *MockClientMockRecorder) GetRemoteID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteID", reflect.TypeOf((*MockClient)(nil).GetRemoteID), arg0)
}

// SendRaftMessage mocks base method.
func (m *MockClient) SendRaftMessage(arg0 context.Context, arg1 *raftpb.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRaftMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRaftMessage indicates an expected call of SendRaftMessage.
func (mr *MockClientMockRecorder) SendRaftMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRaftMessage", reflect.TypeOf((*MockClient)(nil).SendRaftMessage), arg0, arg1)
}
