// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: controller.proto

package controller

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/coreos/etcd/raft/raftpb"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *StatusResponse) Validate() error {
	return nil
}
func (this *AddPeerRequest) Validate() error {
	return nil
}
func (this *GetIDResponse) Validate() error {
	return nil
}
func (this *WriteQuery) Validate() error {
	return nil
}
func (this *Row) Validate() error {
	for _, item := range this.Cells {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Cells", err)
			}
		}
	}
	return nil
}
func (this *Row_Cell) Validate() error {
	if oneOfNester, ok := this.GetValue().(*Row_Cell_Ts); ok {
		if oneOfNester.Ts != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Ts); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Ts", err)
			}
		}
	}
	return nil
}
func (this *QuerySQLRequest) Validate() error {
	return nil
}
func (this *QuerySQLResponse) Validate() error {
	if this.Row != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Row); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Row", err)
		}
	}
	return nil
}
func (this *ExecuteSQLRequest) Validate() error {
	return nil
}
